<?php

namespace App\Actions;

use App\Events\BookingStatusUpdated;
use App\Models\Booking;
use Illuminate\Support\Facades\DB;

/**
 * The "arrived and starting the job" step. start_otp has existed on
 * bookings since Phase 1 (generated by AcceptBookingAction) but nothing has
 * ever verified it — no code path in this app has ever transitioned a
 * booking to 'in_progress' before this action. Built here because Phase
 * B0.2's Worker flow needs a real start step; deliberately NOT required
 * for Provider self-completion, which keeps working exactly as before —
 * CompleteBookingAction already accepts 'assigned'/'provider_en_route'/
 * 'in_progress' as valid starting states, so skipping Start (as every
 * existing Provider flow does today) never blocks completion.
 */
class StartBookingAction
{
    private const STARTABLE_STATUSES = ['assigned', 'provider_en_route'];

    /** @throws \RuntimeException if the booking isn't in a startable state, or the OTP is wrong */
    public function execute(int $bookingId, string $enteredOtp, ?int $changedByUserId = null): Booking
    {
        return DB::transaction(function () use ($bookingId, $enteredOtp, $changedByUserId) {
            $booking = Booking::lockForUpdate()->findOrFail($bookingId);

            if (! in_array($booking->status, self::STARTABLE_STATUSES, true)) {
                throw new \RuntimeException("Booking [{$bookingId}] cannot be started from status '{$booking->status}'.");
            }

            if (empty($booking->start_otp) || $booking->start_otp !== $enteredOtp) {
                throw new \RuntimeException('Incorrect start OTP.');
            }

            $booking->status = 'in_progress';
            $booking->save();

            $booking->statusHistory()->create([
                'status' => 'in_progress',
                'changed_by' => $changedByUserId,
                'note' => 'Started with verified OTP',
                'changed_at' => now(),
            ]);

            event(new BookingStatusUpdated($booking));

            return $booking->fresh();
        });
    }
}
