<?php

namespace App\Actions;

use App\Events\BookingStatusUpdated;
use App\Exceptions\BookingOtpException;
use App\Models\Booking;
use App\Notifications\ProviderJobStatusNotification;
use App\Notifications\Support\ChannelResolver;
use App\Services\BookingOtpService;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * The "arrived and starting the job" step. start_otp has existed on
 * bookings since Phase 1 (generated by AcceptBookingAction) but nothing has
 * ever verified it — no code path in this app has ever transitioned a
 * booking to 'in_progress' before this action. Built here because Phase
 * B0.2's Worker flow needs a real start step; deliberately NOT required
 * for Provider self-completion, which keeps working exactly as before —
 * CompleteBookingAction already accepts 'assigned'/'provider_en_route'/
 * 'in_progress' as valid starting states, so skipping Start (as every
 * existing Provider flow does today) never blocks completion.
 */
class StartBookingAction
{
    private const STARTABLE_STATUSES = ['assigned', 'provider_en_route'];

    /** @throws \RuntimeException if the booking isn't in a startable state, or the OTP is wrong */
    public function execute(int $bookingId, string $enteredOtp, ?int $changedByUserId = null): Booking
    {
        try {
            $booking = DB::transaction(function () use ($bookingId, $enteredOtp, $changedByUserId) {
                $booking = Booking::lockForUpdate()->findOrFail($bookingId);

                if (! in_array($booking->status, self::STARTABLE_STATUSES, true)) {
                    throw new \RuntimeException("Booking [{$bookingId}] cannot be started from status '{$booking->status}'.");
                }

                // Phase E5 — status gate first (an un-startable booking never
                // touches OTP state), then the hardened verify: expiry,
                // attempt cap and single-use, on top of the same plain-string
                // compare and the same "wrong code -> RuntimeException"
                // contract. On success it consumes the code inside this
                // transaction; on a wrong code it throws and the counter
                // increment is committed separately in the catch below,
                // surviving this transaction's rollback.
                app(BookingOtpService::class)->verifyOrFail($booking, 'start', $enteredOtp);

                $booking->status = 'in_progress';
                $booking->save();

                $booking->statusHistory()->create([
                    'status' => 'in_progress',
                    'changed_by' => $changedByUserId,
                    'note' => 'Started with verified OTP',
                    'changed_at' => now(),
                ]);

                event(new BookingStatusUpdated($booking));

                return $booking->fresh();
            });
        } catch (BookingOtpException $e) {
            if ($e->countsAsAttempt) {
                app(BookingOtpService::class)->registerFailedAttempt($bookingId, 'start');
            }
            throw $e;
        }

        // Phase PN1 — post-commit provider notification (job now in
        // progress). Guarded + logged; a transport failure cannot roll back
        // the started booking. Same convention as AcceptBookingAction.
        $this->notifyProviderOfStatus($booking, 'started');

        return $booking;
    }

    private function notifyProviderOfStatus(Booking $booking, string $event): void
    {
        $user = $booking->provider?->user;

        if (! $user) {
            return;
        }

        $channels = ChannelResolver::resolve(array_filter([
            'zone_id' => $booking->zone_id,
            'franchise_id' => $booking->franchise_id,
        ]));

        try {
            $user->notify(new ProviderJobStatusNotification($event, $booking, $channels));
        } catch (\Throwable $e) {
            Log::error("Failed to deliver provider '{$event}' notification for booking [{$booking->id}]: ".$e->getMessage());
        }
    }
}
