<?php

use App\Livewire\Auth\Login;
use App\Livewire\Badges\Manage as BadgesManage;
use App\Livewire\Dashboard;
use App\Livewire\FlashSales\Manage as FlashSalesManage;
use App\Livewire\PerformanceCampaigns\Manage as PerformanceCampaignsManage;
use App\Livewire\Kyc\SupportRequests as KycSupportRequestsManage;
use App\Livewire\Bookings\Index as BookingsIndex;
use App\Livewire\Bookings\Show as BookingsShow;
use App\Livewire\Providers\Index as ProvidersIndex;
use App\Livewire\Providers\Show as ProvidersShow;
use App\Livewire\Customers\Index as CustomersIndex;
use App\Livewire\Customers\Show as CustomersShow;
use App\Livewire\Workers\Index as WorkersIndex;
use App\Livewire\Workers\Show as WorkersShow;
use App\Livewire\Franchises\Manage as FranchisesManage;
use App\Livewire\FranchisePricing\Manage as FranchisePricingManage;
use App\Livewire\Geography\Manage as GeographyManage;
use App\Livewire\Zones\Manage as ZonesManage;
use App\Livewire\Categories\Manage as CategoriesManage;
use App\Livewire\Subcategories\Manage as SubcategoriesManage;
use App\Livewire\Services\Manage as ServicesManage;
use App\Livewire\Banners\Manage as BannersManage;
use App\Livewire\Settings\Manage as SettingsManage;
use App\Livewire\Cms\Manage as CmsManage;
use App\Livewire\Roles\Manage as RolesManage;
use App\Livewire\Payouts\Manage as PayoutsManage;
use App\Livewire\WalletLedger\Index as WalletLedgerIndex;
use App\Livewire\Loyalty\Index as LoyaltyIndex;
use App\Livewire\Commissions\Index as CommissionsIndex;
use App\Livewire\NotificationCenter\Manage as NotificationCenterManage;
use App\Livewire\Operations\Health as OperationsHealth;
use App\Livewire\Payments\Index as PaymentsIndex;
use App\Livewire\Plans\Manage as PlansManage;
use App\Livewire\Subscriptions\Index as SubscriptionsIndex;
use App\Livewire\Chat\Manage as ChatManage;
use App\Livewire\Modules\Manage as ModulesManage;
use App\Livewire\ParcelOrders\Manage as ParcelOrdersManage;
use App\Livewire\Properties\Manage as PropertiesManage;
use App\Livewire\PropertyReservations\Manage as PropertyReservationsManage;
use App\Livewire\TaxiRides\Manage as TaxiRidesManage;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/admin/login', Login::class)->name('admin.login');

Route::post('/admin/logout', function () {
    Auth::logout();
    request()->session()->invalidate();
    request()->session()->regenerateToken();
    return redirect()->route('admin.login');
})->middleware('auth')->name('admin.logout');

Route::middleware(['auth', \App\Http\Middleware\EnsureHasAdminAccess::class])
    ->prefix('admin')
    ->group(function () {
        Route::get('/dashboard', Dashboard::class)->name('admin.dashboard');
        Route::get('/bookings', BookingsIndex::class)->name('admin.bookings.index');
        Route::get('/bookings/{bookingId}', BookingsShow::class)->name('admin.bookings.show');
        Route::get('/providers', ProvidersIndex::class)->name('admin.providers.index');
        Route::get('/providers/{providerId}', ProvidersShow::class)->name('admin.providers.show');
        Route::get('/customers', CustomersIndex::class)->name('admin.customers.index');
        Route::get('/customers/{customerId}', CustomersShow::class)->name('admin.customers.show');
        Route::get('/workers', WorkersIndex::class)->name('admin.workers.index');
        Route::get('/workers/{workerId}', WorkersShow::class)->name('admin.workers.show');
        Route::get('/geography', GeographyManage::class)->name('admin.geography.index');
        Route::get('/franchises', FranchisesManage::class)->name('admin.franchises.index');
        Route::get('/franchises/{franchiseId}/pricing', FranchisePricingManage::class)->name('admin.franchises.pricing');
        Route::get('/zones', ZonesManage::class)->name('admin.zones.index');
        Route::get('/categories', CategoriesManage::class)->name('admin.categories.index');
        Route::get('/subcategories', SubcategoriesManage::class)->name('admin.subcategories.index');
        Route::get('/services', ServicesManage::class)->name('admin.services.index');
        Route::get('/banners', BannersManage::class)->name('admin.banners.index');
        Route::get('/badges', BadgesManage::class)->name('admin.badges.index');
        Route::get('/flash-sales', FlashSalesManage::class)->name('admin.flash-sales.index');
        Route::get('/performance-campaigns', PerformanceCampaignsManage::class)->name('admin.performance-campaigns.index');
        Route::get('/settings', SettingsManage::class)->name('admin.settings.index');
        Route::get('/cms', CmsManage::class)->name('admin.cms.index');
        Route::get('/roles', RolesManage::class)->name('admin.roles.index');
        Route::get('/payouts', PayoutsManage::class)->name('admin.payouts.index');
        Route::get('/wallet-ledger', WalletLedgerIndex::class)->name('admin.wallet-ledger.index');
        Route::get('/loyalty', LoyaltyIndex::class)->name('admin.loyalty.index');
        Route::get('/commissions', CommissionsIndex::class)->name('admin.commissions.index');
        Route::get('/payments', PaymentsIndex::class)->name('admin.payments.index');
        Route::get('/notifications', NotificationCenterManage::class)->name('admin.notifications.index');
        Route::get('/plans', PlansManage::class)->name('admin.plans.index');
        Route::get('/subscriptions', SubscriptionsIndex::class)->name('admin.subscriptions.index');
        Route::get('/operations', OperationsHealth::class)->name('admin.operations.index');
        Route::get('/modules', ModulesManage::class)->name('admin.modules.index');
        Route::get('/parcel-orders', ParcelOrdersManage::class)->name('admin.parcel-orders.index');
        Route::get('/taxi-rides', TaxiRidesManage::class)->name('admin.taxi-rides.index');
        Route::get('/properties', PropertiesManage::class)->name('admin.properties.index');
        Route::get('/property-reservations', PropertyReservationsManage::class)->name('admin.property-reservations.index');
        Route::get('/chat', ChatManage::class)->name('admin.chat.index');
        Route::get('/chat/attachments/{messageId}', [\App\Http\Controllers\Admin\ChatAttachmentController::class, 'show'])->name('admin.chat.attachments.show');
        Route::get('/kyc/support-requests', KycSupportRequestsManage::class)->name('admin.kyc.support-requests.index');
        Route::get('/kyc/documents/provider/{documentId}', [\App\Http\Controllers\Admin\KycDocumentController::class, 'providerDocument'])->name('admin.kyc.documents.provider');
        Route::get('/kyc/documents/field-worker/{documentId}', [\App\Http\Controllers\Admin\KycDocumentController::class, 'fieldWorkerDocument'])->name('admin.kyc.documents.field-worker');
        Route::get('/kyc/videos/{videoId}', [\App\Http\Controllers\Admin\KycDocumentController::class, 'verificationVideo'])->name('admin.kyc.videos.show');
        Route::get('/documents/payments/{paymentId}', [\App\Http\Controllers\Admin\DocumentController::class, 'paymentDocument'])->name('admin.documents.payments.show');
    });
