<?php

namespace App\Livewire\Zones;

use App\Models\Franchise;
use App\Models\Zone;
use Livewire\Component;

class Form extends Component
{
    public ?int $zoneId = null;

    public string $franchiseId = '';
    public string $name = '';
    public string $code = '';
    public string $defaultDispatchRadiusKm = '8';
    public bool $isActive = true;

    // Raw JSON string of [{lat,lng}, ...] fed by the map's drawing tool.
    // Matches the zones.boundary_polygon column shape exactly (array of
    // {lat,lng} points), not the [lat,lng] tuple shape used elsewhere.
    public string $boundaryPolygonJson = '';

    public string $flashMessage = '';

    public function mount(?int $zoneId = null): void
    {
        if ($zoneId) {
            $zone = Zone::findOrFail($zoneId);

            $this->zoneId = $zone->id;
            $this->franchiseId = (string) $zone->franchise_id;
            $this->name = $zone->name;
            $this->code = $zone->code ?? '';
            $this->defaultDispatchRadiusKm = (string) $zone->default_dispatch_radius_km;
            $this->isActive = $zone->is_active;
            $this->boundaryPolygonJson = json_encode($zone->boundary_polygon ?? []);

            // Tells the map JS (in the blade view) to redraw this zone's existing boundary
            $this->dispatch('zone-loaded-for-edit', polygon: $zone->boundary_polygon ?? []);
        }
    }

    public function save(): void
    {
        $this->validate([
            'franchiseId' => ['required', 'exists:franchises,id'],
            'name' => ['required', 'string', 'max:255'],
            'defaultDispatchRadiusKm' => ['required', 'integer', 'min:1', 'max:100'],
        ]);

        $points = json_decode($this->boundaryPolygonJson, true);

        if (! is_array($points) || count($points) < 3) {
            $this->addError('boundaryPolygonJson', 'Draw a boundary with at least 3 points on the map before saving.');
            return;
        }

        $data = [
            'franchise_id' => $this->franchiseId,
            'name' => $this->name,
            'boundary_polygon' => $points,
            'center_lat' => $this->centroid($points, 'lat'),
            'center_lng' => $this->centroid($points, 'lng'),
            'default_dispatch_radius_km' => $this->defaultDispatchRadiusKm,
            'is_active' => $this->isActive,
        ];

        if ($this->zoneId) {
            $zone = Zone::findOrFail($this->zoneId);
            $zone->update($data);
        } else {
            // code is auto-generated by ZoneObserver if left blank
            $zone = Zone::create($data);
            $this->zoneId = $zone->id;
        }

        $this->code = $zone->code;
        $this->flashMessage = 'Saved successfully.';
    }

    /**
     * Simple average-of-points centroid — good enough for storing a rough
     * center point used only as a display/fallback marker, not for the
     * dispatch radius calc itself (that still runs off provider<->customer
     * Haversine distance, per ServiceMatchingJob).
     */
    private function centroid(array $points, string $key): float
    {
        return round(array_sum(array_column($points, $key)) / count($points), 7);
    }

    public function render()
    {
        return view('livewire.zones.form', [
            'franchises' => Franchise::orderBy('name')->get(['id', 'name', 'code']),
        ])->layout('layouts.admin', ['title' => $this->zoneId ? 'Edit Zone' : 'New Zone']);
    }
}
